### PR TITLE
Add logging example and some readme fix ups

### PR DESCRIPTION
**Pull request by lukehinds**
Just getting my feet wet, so some typo fixes and a logging env example.

### CODE REVIEW

**Comment by leonjia0112** [comment]
Thanks for fixing the typo. :+1:

**Comment by frozencemetery** [comment]
Thanks @lukehinds, this looks good!  Don't worry about the Travis failure; rustfmt seems to have changed under us.  Will merge shortly.

**Comment by lukehinds** [comment]
Thanks @leonjia0112 , so the lint errors have crossed over from the master branch.

I can fix these by just running with --check, may as well do this in this branch and we can look at the diffs.

**Comment by frozencemetery** [comment]
Hah, that works too :)

**Comment by lukehinds** [comment]
Sorry @frozencemetery missed your previous comment somehow (comment race condition!). All looks good now.

**Pull request merged**
